version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diploma
    ports:
    - 5433:5432
    volumes:
    - "var/lib/data/postgres"
  diploma:
    image: diploma.jar:latest
    container_name: diploma-recar
    ports:
    - 8080:8080
    depends_on:
      - postgres

volumes:
  data: {}